apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  namespace: default
  name: config-map-updater-role
rules:
  - apiGroups: [""]
    #
    # at the HTTP level, the name of the resource for accessing ConfigMap
    # objects is "configmaps"
    resources: ["configmaps"]
    resourceNames: ["config-service"]
    verbs: ["update", "get"]