kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-cluster-role
rules:
  - apiGroups: [""]
    resources: ["nodes","configmaps"]
    verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: service-account-clusterrolebinding
  labels:
    app: tools-rbac
subjects:
  - kind: ServiceAccount
    name: config-map-updater-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: node-cluster-role
  apiGroup: rbac.authorization.k8s.io